### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#58]
Production:  https://docs.pivotal.io/build-service/0-1-0/release-notes.html

Release Notes:  https://hackmd.io/1bUhKOfmTCa1G1Z2ALfYDg

**Comment by tylerphelan** [comment]
Made a "draft" for release notes and pushed to a branch. https://github.com/pivotal-cf/docs-build-service/blob/release-notes-0.2.0/release-notes.html.md.erb. It's also currently saved in hackermd.

This needs some vetting since I wasn't here for some of these features and compiled them from tracker stories since the last release. 

Also, some of the release notes include versions of dependencies which I did not change as we will need to update all of them right before we release.

For those reasons, putting this down for now and will try to get a pair to work on it with me.
