### ISSUE TITLE
Secrets in Tanzu Build Service 

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#90]
Production: https://docs.pivotal.io/build-service/0-2-0/secrets-in-tbs.html

Things we should document:

Setting up secret syncer and why the user might want to do this

**Comment by tylerphelan** [comment]
Make sure to cover:
- Would be helpful to call out why secret syncing isn't turned on by default so the user can make the best decision.
- Would be helpful here to explain why secret syncing is convenient because it would allow users of the customer's deployment of TBS to access Cluster Builders without needing to create the required secret in individual namespaces

**Comment by tylerphelan** [comment]
Cover the following issues here:
- Cluster builder pulling https://github.com/pivotal-cf/docs-build-service/issues/105
